/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import java.time.LocalDate;
import java.time.LocalTime;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namw2
 */
import deu.cse.lectureroomreservation2.client.Client;
import deu.cse.lectureroomreservation2.client.Student;
import deu.cse.lectureroomreservation2.server.model.GetReservation;
import deu.cse.lectureroomreservation2.server.control.TableRearrange;

public class QuickViewRoom extends javax.swing.JFrame {
    Client client;
    String userid;
    String role;

    /**
     * Creates new form QuickViewRoom
     */
    public QuickViewRoom() {
        initComponents();

        /*
         * Student a = new Student("20213066","홍길동","01012345678");
         * String[][] tempResult = GetReservation.GetTime("reservation");
         * String[][] tempResult2 = GetReservation.GetTime("schedule");
         * TableRearrange.QuickInsertTable2(QuickViewTimeTable, tempResult,
         * tempResult2,a.getId());
         */

    }

    public QuickViewRoom(Client client, String userid, String role) {
        this.client = client;
        this.userid = userid;
        this.role = role;

        initComponents();
        loadQuickTableData();
    }

    private void loadQuickTableData() {
    DefaultTableModel model = (DefaultTableModel) QuickViewTimeTable.getModel();
    model.setRowCount(0);

    // 강의실 목록
    String[] allRooms = {"908", "910", "911", "912", "913", "914", "915", "916", "917", "918"};

    // 오늘 날짜 및 현재 시간
    LocalDate nowDate = LocalDate.now();
    LocalTime nowTime = LocalTime.now();
    String year = String.valueOf(nowDate.getYear());
    String month = String.format("%02d", nowDate.getMonthValue());
    String day = String.format("%02d", nowDate.getDayOfMonth());
    String dayOfWeek = nowDate.getDayOfWeek().getDisplayName(java.time.format.TextStyle.SHORT, java.util.Locale.KOREAN);

    for (String room : allRooms) {
        try {
            // 서버에서 해당 강의실, 요일의 슬롯 리스트 받아오기
            java.util.List<String[]> slots = client.getRoomSlots(room, dayOfWeek);
            for (String[] slot : slots) {
                String start = slot[0]; // 예: "09:00"
                String end = slot[1];   // 예: "09:50"
                // 시작 시간이 현재 시간 이후인지 체크
                LocalTime slotStart = LocalTime.parse(start);
                if (slotStart.isBefore(nowTime)) continue;

                // 날짜 포맷: yyyy / MM / dd / HH:mm HH:mm
                String date = year + " / " + month + " / " + day + " / " + start + " " + end;

                // 서버에서 상태 받아오기
                String state = client.getRoomState(room, dayOfWeek, start, end, date);

                if ("예약 가능".equals(state)) {
                    // 테이블에 추가
                    model.addRow(new Object[]{start, end, room, state, dayOfWeek});
                }
            }
        } catch (Exception e) {
            // 예외 발생 시 해당 강의실은 건너뜀
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuickViewTimeTable = new javax.swing.JTable();
        reservationButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(896, 320));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("빠른 예약");

        QuickViewTimeTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, "공실", null },
                        { null, null, null, "공실", null },
                        { null, null, null, "공실", null },
                        { null, null, null, "공실", null },
                        { null, null, null, "공실", null }
                },
                new String[] {
                        "Time Start", "Time End", "Room", "State", "Day"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(QuickViewTimeTable);

        reservationButton.setText("예약");
        reservationButton.setActionCommand("reservation");
        reservationButton.setPreferredSize(new java.awt.Dimension(100, 50));
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("뒤로가기");
        goBackButton.setActionCommand("goBack");
        goBackButton.setPreferredSize(new java.awt.Dimension(100, 50));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("*빠른예약은 금일 예약만 가능합니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(23, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_reservationButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickViewRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable QuickViewTimeTable;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reservationButton;
    // End of variables declaration//GEN-END:variables
}
