/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.cse.lectureroomreservation2.client.view;

import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import deu.cse.lectureroomreservation2.client.*;

/**
 *
 * @author namw2
 */
public class ViewRoom extends javax.swing.JFrame {

    private static String LastUsedButton = " "; //새로고침 기능을 위해 마지막으로 선택한 버튼 정보를 저장

    /**
     * Creates new form viewRoom
     */
    public ViewRoom() {
        initComponents();

        ImageIcon stairIcon = new ImageIcon(getClass().getResource("/images/stairs.jpg"));
        Image stairImg = stairIcon.getImage().getScaledInstance(60, 110, Image.SCALE_SMOOTH);
        stair1.setIcon(new ImageIcon(stairImg));
        stair2.setIcon(new ImageIcon(stairImg));
        stair1.setText("");
        stair2.setText("");
    }

    public void insertValue(String roomNum) { //테이블에 값을 집어넣는다.

        Student temp = new Student("20213066", "남성우", "01076241028");

        String[][] tempResult = temp.GetTime("reservation");
        String[][] tempResult2 = temp.GetTime("schedule");

        temp.InsertTable(roomNum, (String) DayComboBox.getSelectedItem(), ViewTimeTable, tempResult, tempResult2);

    }

    public void updateColumnValues(JTable table) { //비어있는 칸은 공실로 처리
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            model.setValueAt(" 공실 ", i, 3);
        }
    }

    public void loadData() { //새로고침 기능을 위해 만든 내용 불러오기 함수
        int rowCount = ViewTimeTable.getRowCount(); // 전체 행 개수

        for (int row = 0; row < rowCount; row++) {
            ViewTimeTable.setValueAt(LastUsedButton, row, 2); // 열 인덱스 1번 (두 번째 열)
        }

        this.updateColumnValues(ViewTimeTable);
        this.insertValue(LastUsedButton);

    }

    public void refreshPage() {
        this.loadData();
        Timer timer = new Timer(30_000, e -> {
            System.out.println("30초 경과 - 새로고침 중..."); //TODO 나중에 지우기
            this.loadData(); // 새로고침 동작
        });
        timer.setRepeats(true);
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservationPanel = new javax.swing.JPanel();
        room908 = new javax.swing.JButton();
        room911 = new javax.swing.JButton();
        room912 = new javax.swing.JButton();
        room918 = new javax.swing.JButton();
        room916 = new javax.swing.JButton();
        room915 = new javax.swing.JButton();
        room914 = new javax.swing.JButton();
        room913 = new javax.swing.JButton();
        stair2 = new javax.swing.JLabel();
        elebator = new javax.swing.JLabel();
        stair1 = new javax.swing.JLabel();
        room917 = new javax.swing.JButton();
        room910 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reservationButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        ViewTimePane = new javax.swing.JScrollPane();
        ViewTimeTable = new javax.swing.JTable();
        DayComboBox = new javax.swing.JComboBox<>();
        DayLabel = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reservationPanel.setBackground(new java.awt.Color(255, 255, 255));
        reservationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        room908.setBackground(new java.awt.Color(204, 153, 255));
        room908.setForeground(new java.awt.Color(0, 0, 0));
        room908.setText("<html><center><b>908</b><br>세미나실</center></html>");
        room908.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room908ActionPerformed(evt);
            }
        });

        room911.setBackground(new java.awt.Color(255, 204, 204));
        room911.setForeground(new java.awt.Color(0, 0, 0));
        room911.setText("<html><center><b>911</b><br>실습실</center></html>");
        room911.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room911ActionPerformed(evt);
            }
        });

        room912.setBackground(new java.awt.Color(204, 153, 255));
        room912.setForeground(new java.awt.Color(0, 0, 0));
        room912.setText("<html><center><b>912</b><br>강의실</center></html>");
        room912.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room912ActionPerformed(evt);
            }
        });

        room918.setBackground(new java.awt.Color(255, 204, 204));
        room918.setForeground(new java.awt.Color(0, 0, 0));
        room918.setText("<html><center><b>918</b><br>실습실</center></html>");
        room918.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room918ActionPerformed(evt);
            }
        });

        room916.setBackground(new java.awt.Color(255, 204, 204));
        room916.setForeground(new java.awt.Color(0, 0, 0));
        room916.setText("<html><center><b>916</b><br>실습실</center></html>");
        room916.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room916ActionPerformed(evt);
            }
        });

        room915.setBackground(new java.awt.Color(255, 204, 204));
        room915.setForeground(new java.awt.Color(0, 0, 0));
        room915.setText("<html><center><b>915</b><br>실습실</center></html>");
        room915.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room915ActionPerformed(evt);
            }
        });

        room914.setBackground(new java.awt.Color(204, 153, 255));
        room914.setForeground(new java.awt.Color(0, 0, 0));
        room914.setText("<html><center><b>914</b><br>강의실</center></html>");
        room914.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room914ActionPerformed(evt);
            }
        });

        room913.setBackground(new java.awt.Color(204, 153, 255));
        room913.setForeground(new java.awt.Color(0, 0, 0));
        room913.setText("<html><center><b>913</b><br>강의실</center></html>");
        room913.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room913ActionPerformed(evt);
            }
        });

        stair2.setText("jLabel2");

        elebator.setText("엘베 사진");

        stair1.setText("jLabel6");

        room917.setBackground(new java.awt.Color(255, 255, 204));
        room917.setForeground(new java.awt.Color(0, 0, 0));
        room917.setText("917");

        room910.setBackground(new java.awt.Color(153, 204, 255));
        room910.setForeground(new java.awt.Color(0, 0, 0));
        room910.setText("910");

        javax.swing.GroupLayout reservationPanelLayout = new javax.swing.GroupLayout(reservationPanel);
        reservationPanel.setLayout(reservationPanelLayout);
        reservationPanelLayout.setHorizontalGroup(
            reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationPanelLayout.createSequentialGroup()
                        .addComponent(room918, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room917, javax.swing.GroupLayout.PREFERRED_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(reservationPanelLayout.createSequentialGroup()
                        .addComponent(room908, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elebator, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reservationPanelLayout.createSequentialGroup()
                        .addComponent(room916, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room915, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room914, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room913, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reservationPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(stair1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(room910, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room911, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room912, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stair2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        reservationPanelLayout.setVerticalGroup(
            reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(room908, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room911, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room912, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stair2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elebator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(room910, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(reservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(room918, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room916, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room915, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room914, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room913, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(room917, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("조회&예약");

        reservationButton.setText("예약");
        reservationButton.setActionCommand("reservation");
        reservationButton.setPreferredSize(new java.awt.Dimension(100, 50));
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("뒤로가기");
        goBackButton.setActionCommand("goBack");
        goBackButton.setPreferredSize(new java.awt.Dimension(100, 50));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        ViewTimeTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ViewTimeTable.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        ViewTimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00", "09:50", null, " 공실 "},
                {"10:00", "10:50", null, " 공실 "},
                {"11:00", "11:50", null, " 공실 "},
                {"12:00", "12:50", null, " 공실 "},
                {"13:00", "13:50", null, " 공실 "},
                {"14:00", "14:50", null, " 공실 "},
                {"15:00", "15:50", null, " 공실 "},
                {"16:00", "16:50", null, " 공실 "},
                {"17:00", "17:50", null, " 공실 "}
            },
            new String [] {
                "Title Start", "Time End", "Room", "State"
            }
        )
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // 모든 셀 편집 비활성화
            }
        }
    );
    ViewTimeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    ViewTimeTable.setDoubleBuffered(true);
    ViewTimeTable.setGridColor(new java.awt.Color(0, 0, 0));
    ViewTimePane.setViewportView(ViewTimeTable);

    DayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "월", "화", "수", "목", "금" }));

    DayLabel.setText("요일:");

    RefreshButton.setText("새로고침");
    RefreshButton.setActionCommand("reservation");
    RefreshButton.setPreferredSize(new java.awt.Dimension(100, 50));
    RefreshButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            RefreshButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ViewTimePane)
                        .addComponent(reservationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16))))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(reservationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(ViewTimePane, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(reservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(15, 15, 15))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void room916ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room916ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "916";
        this.refreshPage();
    }//GEN-LAST:event_room916ActionPerformed

    private void room918ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room918ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "918";
        this.refreshPage();
    }//GEN-LAST:event_room918ActionPerformed

    private void room908ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room908ActionPerformed
        // TODO add your handling code here:

        LastUsedButton = "908";

        this.refreshPage();
    }//GEN-LAST:event_room908ActionPerformed

    private void room911ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room911ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "911";
        this.refreshPage();
    }//GEN-LAST:event_room911ActionPerformed

    private void room912ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room912ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "912";
        this.refreshPage();
    }//GEN-LAST:event_room912ActionPerformed

    private void room913ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room913ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "913";
        this.refreshPage();
    }//GEN-LAST:event_room913ActionPerformed

    private void room914ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room914ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "914";
        this.refreshPage();
    }//GEN-LAST:event_room914ActionPerformed

    private void room915ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room915ActionPerformed
        // TODO add your handling code here:
        LastUsedButton = "915";
        this.refreshPage();
    }//GEN-LAST:event_room915ActionPerformed

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
        LastUsedButton = " ";
        this.dispose();

    }//GEN-LAST:event_reservationButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        // new tempMainpage().setVisible(true);
        LastUsedButton = " ";
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        this.refreshPage();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayComboBox;
    private javax.swing.JLabel DayLabel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JScrollPane ViewTimePane;
    private javax.swing.JTable ViewTimeTable;
    private javax.swing.JLabel elebator;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reservationButton;
    private javax.swing.JPanel reservationPanel;
    private javax.swing.JButton room908;
    private javax.swing.JButton room910;
    private javax.swing.JButton room911;
    private javax.swing.JButton room912;
    private javax.swing.JButton room913;
    private javax.swing.JButton room914;
    private javax.swing.JButton room915;
    private javax.swing.JButton room916;
    private javax.swing.JButton room917;
    private javax.swing.JButton room918;
    private javax.swing.JLabel stair1;
    private javax.swing.JLabel stair2;
    // End of variables declaration//GEN-END:variables
}
